### PR TITLE
Upgrade to Angular 8

### PR DESCRIPTION
**Pull request by hupf**
* Upgrade to Angular 8 & update all dependencies
* Introduce `npm run build_lib` command that builds lib and copies README.md/LICENSE files from project root
* Fix tests of the ngx-summernote-app
* Bump version to 0.7.0
* Add Angular-compatibility table to README.md

I've tested the functionality of the directive using the example app. So far everything looks fine.

### CODE REVIEW

**Comment by hupf** [comment]
@lula Anything I can help to get this merged?

**Comment by guiomesch** [comment]
@lula is it possible to merge this pull request please ?

**Comment by lula** [comment]
Hello guys! thanks for the PR! In the last months I've been super busy with work (still are...), I bought my new home, I'm checking construction works, moving in.... in 4 letters: HELL!

To be honest I've seen lots of issues, and this PR but I never checked. I'll merge it right now.

Sorry and thanks again! 🙏 🙏 🙏 

Luca

**Comment by hupf** [comment]
Thanks @lula for the merge and have a nice move-in – I hope hell will soon cool down a bit for you :wink:

**Comment by lula** [comment]
Thanks @hupf !!!!

**Comment by hupf** [comment]
I have one more request to the busy man. Can you please publish the new 0.7.0 version to NPM? BTW you can use the new `npm run build_lib` to copy the README as well...

**Comment by lula** [comment]
it should be published now :)

**Pull request merged**
