### PR TITLE
Added option to handle image upload to server instead of base64

### PR DESCRIPTION
**Pull request by ishan123456789**
Just add path where you want to insert the image
API call must return a path in response regarding #6

### CODE REVIEW

**Comment by ishan123456789** [comment]
Thanks for considering my proposal and I'll love to clarify on the functions I used:
As stated in readme the API call should return a response : { path: 'path-to-file' }
The main idea behind what I did came from frola functionality frola is a paid WYSWIG editor and I didn't wanted to put any money for something that is available for free. So I wanted to make this open source one better.

### point 1:

Here's a detailed description of the functionality:
```
       if (this._options.uploadImagePath) { // Checks if user specified a URL to upload image to

            this.http.post(this._options.uploadImagePath, data)
                .pipe(
                    map((response: { path: string }) => response && typeof response.path === 'string' && response.path), // This pipe strips path key from the API response and gives ahead to be subscribed
                    catchError(e => { // if any thing goes wrong this catch will throw an error with blank path to be subscribed
                        throwError('An error occured while uploading' + e);
                        return of('');
                    }))
                .subscribe(dataIn => {
                    if (dataIn) { // So after being piped this variable contains either the `path` or a blank string which is considered to be equal to false == ''
                        this._$element.summernote('insertImage', dataIn);
                        this.imageUpload.emit({ status: 'off' });
                    } else {
                        this.insertNormally(files); // This is what goes by default so if something goes wrong then a base 64 is inserted by default
                    }
                }, (e) => {
                    this.insertNormally(files);
                });
```

Hi I've explained the main lines and the points above please let me know if still any other clarification needed.

###point 2:
As already stated I took the idea from frola. The main reason to upload to server is that it makes the WYSWIG content too heavy to handle and that's the main reason why frola has an option to upload to server. Consider a MongoDB collection or MYSql db if you're thinking of uploading multiple 2 MB image in the content then you're surely loosing money in the hosting and the other thing is that it'll make the content getting process slow with high payload to handle for server. so the rendering process of your content is slowed highly. So this is the problem this PR will solve.

**Comment by lula** [comment]
Have you ever tried 🤔?

```
if (dataIn) { // this is true or false
                        this._$element.summernote('insertImage', dataIn);
```

Anyway even if dataIn was the path (string), I still don't see the purpose of adding it of the uploaded image in the editor.

The rest makes sense.

**Comment by hitpopdimestop** [comment]
@lula, @ishan123456789 thanks for spending your time for making this editor better. I'll give my feedback on both points you stated.

1. I checked the map function to be sure it returns string - everything is ok there. Check this snippet:
https://jsbin.com/relusitaja/2/edit?js,console

2. @ishan123456789 said it right - if we put lots of heavy images inside our wysiwyg editor it becomes lots of data to send via HTTP in a single request and lots of data to store in our database. It is much better to store only links to those images and the browser would even cache them for us.

**Comment by ishan123456789** [comment]
The datain will contain the path ie. http://example.com/example.jpg
This will insert the image from the specified URL to the editor.
@lula

**Comment by lula** [comment]
Guys, you were right, it does return the path. I possibly did some kind of mistake myself (or I was drunk). Sorry for that!

I'll merge the PR in the coming days. Thanks!!!

**Comment by lula** [comment]
Hello guys! 0.6.0 is released! It includes this PR, slightly modified:

- new methods and injected HttpClient set to private
- method `insertNormally` renamed to `insertFromDataURL`
- imageUpload emits `{ uploading: true|false, encoding?: 'base64' }`. Concerning with this, I thought it would be easier to have a boolean, rather than 'on' or 'off' as string. Please let me know if I well understood the meaning of `status: 'on'|'off', and/or indicate the reasons why you would prefer to have strings rather than boolean.

Thanks again for your work, @ishan123456789 ! Much appreciated!!!

**Pull request merged**
