### PR TITLE
Added event on image delete

### PR DESCRIPTION
**Pull request by tim-boerner**
Added event on media delete which can be used to delete resources on server

### CODE REVIEW

**Comment by lula** [comment]
Hey @tim-boerner! Thanks for contributing in this project! 🎉 🎉 🎉 

0.7.2 is out!

**Comment by lula** [comment]
I made other changes where I forgot to set callbacks by mistake. 0.7.3 should resolve this.

**Comment by tim-boerner** [comment]
Alright, i noticed that the merge for 0.7.2 somehow went wrong ;-)

**Comment by lula** [comment]
Very wrong 😆 ! Sorry for this!

**Pull request merged**
