### PR TITLE
Upgrade to angular 14 (Ivy compatibility)

### LINKED ISSUE #145: Ivy distribution
Angular 13 produces the following warning:

```
⠹ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-summernote [es2015/esm2015] (https://github.com/lula/ngx-summernote.git)
Encourage the library authors to publish an Ivy distribution.
```

Any chance this could be addressed? My understanding is that Ivy for libs will be required in Angular 14.

### PR DESCRIPTION
**Pull request by floAtEbcont**
Fixes #145

### CODE REVIEW

**Comment by dancornilov** [comment]
@llulani Hey, it's possible to merge this think? Because now this package is not compatible with Ivy, and we cannot update the version of whole project. 

Thanks in advance

**Comment by ManuBucaciuc** [comment]
Do we have any updates regarding this issue? Making this library Ivy compatible would be awesome in order to update my project to latest Angular version 🙏 .

Thank you for your work!

**Comment by lula** [comment]
Hi everyone! I'm quite busy with work and unfortunately I only have a little time spare 😞 . Anyways, this PR has been merged into version 1.0.0! Many thanks to @floAtEbcont who did the actual job 💪 🙏

**Comment by lula** [comment]
@floAtEbcont thank you for your help 🙏 ! It would be wonderful if you'd like to join as a contributor of this repo. Would you consider it?

**Comment by floAtEbcont** [comment]
@lula Oh... No, I'm afraid I've got too much on my hands already to be added as a contributor. But thank you for your trust :)

**Comment by lula** [comment]
@floAtEbcont I understand. Thank you anyway! 😄

**Pull request merged**
